version: '3.8'

services:
  health_check:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/automation
    command: /bin/sh -c "ls -la && pytest -m health"
    working_dir: /automation
#    environment:
#      - DB_USER=${DB_USER}