version: "3.8"

services:
  helthcheck:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/automation
    command: /bin/sh -c "ls -la && pytest -m db2"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_USER}
      - DB_NAME=${DB_USER}
      - DB_PORT=${DB_USER}
      - DB_HOST=${DB_USER}

