version: "3.8"

services:
  regression:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /automation
    volumes:
      - ./:/automation

    command: /bin/sh -c "ls -ls && pytest -m db2 --alluredir=allure-results"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
