name: Running Health Check

on: workflow_dispatch

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Running docker-compose and tests
        run: |
          docket-compose up --exit-code-from helthcheck || true