name: Health Check

on: workflow_dispatch

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run docker-compose
#        env:
#          DB_USER: ${{ secret.DB_USER }}
        run: |
          docker-compose up --exit-code-from healthcheck || true
