name: Health Check Test

on: workflow_dispatch

jobs:
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3
      - name: Run docker-compose
        run: |
          docker-compose up --exit-code-from healthcheck || true